<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FD_JOB_Nov2019</name>
   <tag></tag>
   <elementGuidId>17ba3b88-04e8-4f7b-99c9-8d70538f7331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='slds-listbox__item'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'FD_JOB_Nov2019' or . = 'FD_JOB_Nov2019')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-listbox__option-text slds-listbox__option-text_entity</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>25:4942;a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FD_JOB_Nov2019</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content-id-1&quot;)/article[1]/div[1]/div[@class=&quot;content&quot;]/div[@class=&quot;slds-card__body slds-card__body_inner centerWrapper flowruntimeBody&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;cFiberDeepScreen&quot;]/div[@class=&quot;slds-grid slds-wrap&quot;]/div[@class=&quot;slds-p-around_large slds-size_6-of-12 slds-small-size_12-of-12 slds-medium-size_6-of-12&quot;]/div[@class=&quot;slds-form-element slds-lookup slds-is-open cCustomLookup&quot;]/ul[@class=&quot;slds-listbox slds-listbox_vertical slds-dropdown slds-dropdown_fluid slds-lookup__menu slds&quot;]/li[@class=&quot;slds-listbox__item&quot;]/span[@id=&quot;listbox-option-unique-id-01&quot;]/span[@class=&quot;slds-media__body&quot;]/span[@class=&quot;slds-listbox__option-text slds-listbox__option-text_entity&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//span[@id='listbox-option-unique-id-01']/span[2]/span)[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of icon'])[2]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='icon'])[4]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='icon'])[5]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of icon'])[3]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/span[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
