<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReserveQtyValueInGrid</name>
   <tag></tag>
   <elementGuidId>490ae96b-91db-48eb-94b4-5ed2d342542d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[contains(@class,'graybackGroundColor')]//td[7]//div[contains(@class,'slds-truncate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
